/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author ducng
 */
public class MainForm extends javax.swing.JFrame {

    /** Creates new form MainForm */
    public MainForm() {
        initComponents();
        setTitle("Sudoku Game");
        setLocation(300, 100);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuPanel = new javax.swing.JPanel();
        name = new javax.swing.JLabel();
        level = new javax.swing.JLabel();
        easy = new javax.swing.JRadioButton();
        normal = new javax.swing.JRadioButton();
        hard = new javax.swing.JRadioButton();
        savegame = new javax.swing.JButton();
        loadgame = new javax.swing.JButton();
        quit = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        check = new javax.swing.JButton();
        sloove = new javax.swing.JButton();
        newgame = new javax.swing.JButton();
        time = new javax.swing.JLabel();
        ptime = new javax.swing.JTextField();
        logo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        custom = new javax.swing.JRadioButton();
        menuBar = new javax.swing.JMenuBar();
        menuFIle = new javax.swing.JMenu();
        saveGame = new javax.swing.JMenuItem();
        loadGame = new javax.swing.JMenuItem();
        exit = new javax.swing.JMenuItem();
        help = new javax.swing.JMenu();
        about = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        menuPanel.setBackground(new java.awt.Color(229, 226, 209));

        name.setFont(new java.awt.Font("Arial", 0, 16)); // NOI18N
        name.setText("Sudoku Game");
        name.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        name.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        level.setBackground(new java.awt.Color(229, 226, 209));
        level.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        level.setText("Level: ");

        easy.setBackground(new java.awt.Color(229, 226, 209));
        easy.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        easy.setText("Easy");
        easy.setBorder(null);

        normal.setBackground(new java.awt.Color(229, 226, 209));
        normal.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        normal.setText("Normal");
        normal.setBorder(null);

        hard.setBackground(new java.awt.Color(229, 226, 209));
        hard.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        hard.setText("Hard");
        hard.setBorder(null);

        savegame.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        savegame.setText("Save Game");
        savegame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                savegameMouseClicked(evt);
            }
        });
        savegame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savegameActionPerformed(evt);
            }
        });

        loadgame.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loadgame.setText("Load Game");
        loadgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadgameMouseClicked(evt);
            }
        });

        quit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        quit.setText("Quit");
        quit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                quitMouseClicked(evt);
            }
        });
        quit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(16, 16, 16));

        check.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        check.setText("Check");

        sloove.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        sloove.setText("Slove");

        newgame.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        newgame.setText("New Game");
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });

        time.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        time.setText("Time:");

        ptime.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        ptime.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        ptime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ptimeActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(16, 16, 16));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel1.setText("Point");

        jTextField1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        custom.setBackground(new java.awt.Color(229, 226, 209));
        custom.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        custom.setText("Custom");
        custom.setBorder(null);

        org.jdesktop.layout.GroupLayout menuPanelLayout = new org.jdesktop.layout.GroupLayout(menuPanel);
        menuPanel.setLayout(menuPanelLayout);
        menuPanelLayout.setHorizontalGroup(
            menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSeparator2)
            .add(menuPanelLayout.createSequentialGroup()
                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(menuPanelLayout.createSequentialGroup()
                        .add(157, 157, 157)
                        .add(logo)
                        .add(0, 0, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jSeparator1)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, menuPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(check, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(menuPanelLayout.createSequentialGroup()
                                .add(time)
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(ptime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 83, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                        .add(18, 18, 18)
                        .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(menuPanelLayout.createSequentialGroup()
                                .add(sloove, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                .add(16, 16, 16))
                            .add(menuPanelLayout.createSequentialGroup()
                                .add(jLabel1)
                                .add(18, 18, 18)
                                .add(jTextField1)
                                .add(15, 15, 15)))))
                .addContainerGap())
            .add(menuPanelLayout.createSequentialGroup()
                .add(114, 114, 114)
                .add(name)
                .add(0, 0, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(menuPanelLayout.createSequentialGroup()
                        .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(menuPanelLayout.createSequentialGroup()
                                .add(level)
                                .add(26, 26, 26)
                                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(easy, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(hard, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(newgame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(menuPanelLayout.createSequentialGroup()
                                .add(48, 48, 48)
                                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(custom, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 93, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(normal, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, menuPanelLayout.createSequentialGroup()
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .add(savegame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(menuPanelLayout.createSequentialGroup()
                        .add(loadgame, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .add(quit, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 120, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(24, 24, 24))
        );
        menuPanelLayout.setVerticalGroup(
            menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(menuPanelLayout.createSequentialGroup()
                .addContainerGap()
                .add(name, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 36, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(level)
                    .add(easy)
                    .add(normal))
                .add(16, 16, 16)
                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(hard)
                    .add(custom))
                .add(18, 18, 18)
                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(newgame)
                    .add(savegame))
                .add(18, 18, 18)
                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(loadgame)
                    .add(quit))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 20, Short.MAX_VALUE)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(check)
                    .add(sloove))
                .add(18, 18, 18)
                .add(menuPanelLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(time)
                    .add(ptime, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 24, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel1)
                    .add(jTextField1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(53, 53, 53)
                .add(logo)
                .add(226, 226, 226))
        );

        menuFIle.setText("File");
        menuFIle.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        menuFIle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menuFIleMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                menuFIleMouseEntered(evt);
            }
        });

        saveGame.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        saveGame.setText("Save game");
        saveGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                saveGameMouseClicked(evt);
            }
        });
        menuFIle.add(saveGame);

        loadGame.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        loadGame.setText("Load game");
        loadGame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loadGameMouseClicked(evt);
            }
        });
        menuFIle.add(loadGame);

        exit.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        exit.setText("Exit");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });
        menuFIle.add(exit);

        menuBar.add(menuFIle);

        help.setText("Help");
        help.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N

        about.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        about.setText("About");
        help.add(about);

        menuBar.add(help);

        setJMenuBar(menuBar);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(0, 512, Short.MAX_VALUE)
                .add(menuPanel, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 308, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(menuPanel, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void savegameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savegameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savegameActionPerformed

    private void loadgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadgameMouseClicked
        // TODO add your handling code here:
        ChoseFile choseFile = new ChoseFile();
        choseFile.setVisible(true);
    }//GEN-LAST:event_loadgameMouseClicked

    private void quitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_quitActionPerformed

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newgameActionPerformed

    private void ptimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ptimeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ptimeActionPerformed

    private void savegameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_savegameMouseClicked
        // TODO add your handling code here:
        ChoseFile choseFile = new ChoseFile();
        choseFile.setVisible(true);
    }//GEN-LAST:event_savegameMouseClicked

    private void menuFIleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFIleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFIleMouseClicked

    private void loadGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loadGameMouseClicked
        // TODO add your handling code here:
        ChoseFile choseFile = new ChoseFile();
        choseFile.setVisible(true);
    }//GEN-LAST:event_loadGameMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_exitMouseClicked

    private void saveGameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_saveGameMouseClicked
        // TODO add your handling code here:
        ChoseFile choseFile = new ChoseFile();
        choseFile.setVisible(true);
    }//GEN-LAST:event_saveGameMouseClicked

    private void menuFIleMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menuFIleMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_menuFIleMouseEntered

    private void quitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quitMouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_quitMouseClicked


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem about;
    private javax.swing.JButton check;
    private javax.swing.JRadioButton custom;
    private javax.swing.JRadioButton easy;
    private javax.swing.JMenuItem exit;
    private javax.swing.JRadioButton hard;
    private javax.swing.JMenu help;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel level;
    private javax.swing.JMenuItem loadGame;
    private javax.swing.JButton loadgame;
    private javax.swing.JLabel logo;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuFIle;
    private javax.swing.JPanel menuPanel;
    private javax.swing.JLabel name;
    private javax.swing.JButton newgame;
    private javax.swing.JRadioButton normal;
    private javax.swing.JTextField ptime;
    private javax.swing.JButton quit;
    private javax.swing.JMenuItem saveGame;
    private javax.swing.JButton savegame;
    private javax.swing.JButton sloove;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables

}
